feat: Pre-commit and pre-push checks added

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -4,8 +4,18 @@
 echo ""
 echo -e "\033[1;33mRunning pre-commit tests..\033[0m"
 echo ""
-npx --no -- commitlint --edit 
-echo ""
-echo ""
-echo -e "\033[1;33mAll files are good to push\033[0m"
-echo ""
+
+# Run commitlint
+
+# Check the exit status of commitlint
+if npx commitlint --edit ; then
+  echo ""
+  echo -e "\033[0;32m✅✅ All files are good to push...\033[0m"
+  echo ""
+  exit 0
+else
+  echo ""
+  echo -e "\033[0;31m😱😱 There is some typo in commit message as above... 😱😱\033[0m"
+  echo ""
+  exit 1
+fi
diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,7 +2,17 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 echo ""
-echo -e "\033[1;33mRunning formating & lint tests on staged files..\033[0m"
+echo -e "\033[1;33m📍 Running formatting & lint tests on staged files..\033[0m"
 echo ""
-npm run lint-staged
 
+if npm run pre-commit; then
+  echo ""
+  echo -e "\033[0;32m✅✅Staged files checks passed & have no errors...\033[0m"
+  echo ""
+  exit 0
+else
+  echo ""
+  echo -e "\033[0;31m😅😅Staged files have above errors..😅😅\033[0m"
+  echo ""
+  exit 1
+fi
